const patinaContent = {
    EN:{
        navMenuHome: "Home",
        navMenuProduct:"Gallery",
        navMenuProject:"Project",
        navMenuService:"Service",
        homeAboutMainTitle:"A few words",
        homeAboutSubTitle:"About us",
        homeAboutDescription:"Interior Studio was founded in 1993 and has become locally and nationally recognized as a leading Interior Design Firm. Innovative techniques, customized interior planning, and impeccable service have allowed us to skyrocket to success and maintain a strong and loyal clientele.",
        homeAboutItemProject:"Projects",
        homeAboutItemEmployees:"Employees",
        homeAboutItemProducts:"Products",
        homeAboutItemClient:"Clients",
        homeAboutItemMore:"more than",
        homeAboutItemProjectNumber:"560",
        homeAboutItemEmployeesNumber:"50",
        homeAboutItemProductsNumber:"1000",
        homeAboutItemClientNumber:"300",
        homeDetailTitle:"EXCLUSIVE INTERIOR ",
        homeDetailSubTitle:"DESIGN IS OUR PHILOSOPHY",
        homeDetailDescription:"Providing authentic and mindful spaces that are 100% customized to each client has been and always will be the number one priority for the designers at Interior Studio.",
        homeReasonTitle1:"Architecture",
        homeReasonDescription1:"The essence of our development process is to reinvent spaces and environments.",
        homeReasonTitle2:"Interior Design",
        homeReasonDescription2:"The essence of our development process is to reinvent spaces and environments.",
        homeReasonTitle3:"Urban Design",
        homeReasonDescription3:"The essence of our development process is to reinvent spaces and environments.",
        category1:"Chairs",
        category2:"Tables",
        category3:"Lamps",
        category4:"Sofas",
        category5:"Beds"
    },
    VN:{
        navMenuHome: "Trang chủ",
        navMenuProduct:"Sản phẩm", 
        navMenuProject:"Dự án",
        navMenuService:"Dịch vụ",
        homeAboutMainTitle:"Đôi dòng",
        homeAboutSubTitle:"Về chúng tôi",
        homeAboutDescription:"Interior Studio was founded in 1993 and has become locally and nationally recognized as a leading Interior Design Firm. Innovative techniques, customized interior planning, and impeccable service have allowed us to skyrocket to success and maintain a strong and loyal clientele.",
        homeAboutItemProject:"Dự án",
        homeAboutItemEmployees:"Nhân viên",
        homeAboutItemProducts:"Sản phẩm",
        homeAboutItemClient:"khách hàng",
        homeAboutItemMore:"hơn",
        homeAboutItemProjectNumber:"560",
        homeAboutItemEmployeesNumber:"50",
        homeAboutItemProductsNumber:"1000",
        homeAboutItemClientNumber:"300",
        homeDetailTitle:"EXCLUSIVE INTERIOR ",
        homeDetailSubTitle:"DESIGN IS OUR PHILOSOPHY",
        homeDetailDescription:"Providing authentic and mindful spaces that are 100% customized to each client has been and always will be the number one priority for the designers at Interior Studio.",
        homeReasonTitle1:"Architecture",
        homeReasonDescription1:"The essence of our development process is to reinvent spaces and environments.",
        homeReasonTitle2:"Interior Design",
        homeReasonDescription2:"The essence of our development process is to reinvent spaces and environments.",
        homeReasonTitle3:"Urban Design",
        homeReasonDescription3:"The essence of our development process is to reinvent spaces and environments.",
        category1:"Ghế",
        category2:"Bàn",
        category3:"Đèn ngủ",
        category4:"Sofa",
        category5:"Giường"
    }
};
export default patinaContent;

