export const ProductSrc = [
    {
        id:1,
        imgsrc:"../asset/pic1.jpg",
        category:"Chairs",
        height:"140px",
    },
    {
        id:2,
        imgsrc:"../asset/pic2.jpg",
        category:"Chairs",
        height:"180px",
    },
    {
        id:3,
        imgsrc:"../asset/pic3.jpg",
        category:"Chairs",
        height:"160px",
    },
    {
        id:4,
        imgsrc:"../asset/pic4.jpg",
        category:"Chairs",
        height:"220px",
    },
    {
        id:5,
        imgsrc:"../asset/pic5.jpg",
        category:"Chairs",
        height:"180px",
    },
    {
        id:6,
        imgsrc:"../asset/pic6.jpg",
        category:"Chairs",
        height:"240px",
    },
    {
        id:7,
        imgsrc:"../asset/pic7.jpg",
        category:"Chairs",
        height:"200px",
    },
    {
        id:8,
        imgsrc:"../asset/pic8.jpg",
        category:"Chairs",
        height:"180px",
    },
    {
        id:9,
        imgsrc:"../asset/pic9.jpg",
        category:"Chairs",
        height:"220px",
    },
    {
        id:10,
        imgsrc:"../asset/pic10.jpg",
        category:"Lamps",
        height:"160px",
    },
    {
        id:11,
        imgsrc:"../asset/pic11.jpg",
        category:"Lamps",
        height:"140px",
    },
    {
        id:12,
        imgsrc:"../asset/pic12.jpg",
        category:"Lamps",
        height:"180px",
    },
    {
        id:13,
        imgsrc:"../asset/pic13.jpg",
        category:"Lamps",
        height:"220px",
    },

]

export const categories = [
    {
        name:"Chairs",
        key:"category1"
    },
    {
        name:"Tables",
        key:"category2"
    },
    {
        name:"Lamps",
        key:"category3"
    },
    {
        name:"Sofas",
        key:"category4"
    },
    {
        name:"Beds",
        key:"category5"
    },

]
